### PR TITLE
Add all the RFC2616 HTTP methods to the test client

### PR DESCRIPTION
**Pull request by nashe**
This aims to fix the issue #514.

### CODE REVIEW

**Comment by Changaco** [comment]
Looks fine to me, though some of the "x" names are a little weird. What do you think @whit537? Maybe we should just switch to an underscore at the end instead of an "x" for the first vowel?

**Comment by nashe** [comment]
Or prefix the method by a `x`, to keep this "eXcept" idea?

**Comment by whit537** [comment]
Looks good to me. I say we accept it as-is.

**Comment by whit537** [comment]
Thanks @nashe! :)

**Pull request merged**
