### PR TITLE
Bring back `whence_raised`

### LINKED ISSUE #282: we seem to have lost whence_raised
This is another #262 regression. We call `sys.exc_clear` in algorithm after any exception handler, so the `exc_info` call in `log_result_of_response` always returns nothing.

If we were under Python 3, we would have the traceback object stored on the exception. I decided not to shim that for Python 2 in Algorithm.py. We might review that decision, but for now I propose that we modify `get_response_for_exception` to store the current traceback object on the response, for use downstream in `log_result_of_response`. Let's be careful not to create a circular reference with the traceback object, per the Python 2 docs:

> **Warning:** Assigning the traceback return value to a local variable in a function that is handling an exception will cause a circular reference. This will prevent anything referenced by a local variable in the same function or by the traceback from being garbage collected. Since most functions don’t need access to the traceback, the best solution is to use something like `exctype, value = sys.exc_info()[:2]` to extract only the exception type and value. If you do need the traceback, make sure to delete it after use (best done with a `try ... finally` statement) or to call `exc_info()` in a function that does not itself handle an exception.
> 
> http://docs.python.org/2/library/sys.html#sys.exc_info

### PR DESCRIPTION
**Pull request by Changaco**
This PR aims to close #282. We already log the full traceback, so why fix `whence_raised`? And if we're not going to fix it, then why keep it?

### CODE REVIEW

**Comment by whit537** [comment]
> We already log the full traceback

Do we? Even for 200s and 300s?

**Comment by Changaco** [comment]
> Even for 200s and 300s?

No, you're right, we only show tracebacks for 500s.

If we want the location for all raised responses then we'll need to call `whence_raised()` from inside the exception handlers and put it in the state like the traceback.

**Comment by whit537** [comment]
> If we want the location for all raised responses

I think of `whence_raised` as an occasional debugging aid (_very_ occasional these days, since it's broken ;). I don't think we need to have it in the default algorithm, but I think it's a useful tool to have available for complex bugs.

**Comment by Changaco** [comment]
Okay, here's a fix.

**Comment by Changaco** [comment]
Grr, Windows file paths.

**Comment by whit537** [comment]
wfm 👍

**Pull request merged**
