### PR TITLE
Add support for python3

### LINKED ISSUE #493: Support Python 3.x
The world is changing.  We should change with it.

### PR DESCRIPTION
**Pull request by Changaco**
Closes #493. Uses `six` and `tox`.

I dropped support for HTTP Digest auth because I didn't want to spend time porting code that nobody is going to use anyway.

### CODE REVIEW

**Comment by Changaco** [comment]
Travis and AppVeyor are now both green. Ready for review.

**Comment by Changaco** [comment]
I found a few bugs by running Liberapay on top of this branch. One of them isn't actually from this branch but I'm going to put the fix here anyway to avoid spending time rebasing.

**Comment by Changaco** [comment]
I now have Liberapay running on python3 on top of this branch! \o/

**Comment by Changaco** [comment]
(BTW, I reported the response header type issue upstream: <https://github.com/benoitc/gunicorn/issues/1340>.)

**Comment by whit537** [comment]
> I dropped support for HTTP Digest auth because I didn't want to spend time porting code that nobody is going to use anyway.

Okay.

@pjz Feel free to re-PR this once the dust settles, if you're still interested. :)

**Pull request merged**
