### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by Changaco**
Next step in documenting Pando. WIP.

### CODE REVIEW

**Comment by Changaco** [comment]
I've pointed RtD to this branch.

**Comment by Changaco** [comment]
Ready for review. There's more to do of course, but I can make another PR.

**Comment by whit537** [comment]
@Changaco Is RtD automatically building the branch for you? Over on aspen.py I've been building it manually, I think it might be misconfigured.

**Comment by Changaco** [comment]
It was correctly building the `docs` branch, yes. Hopefully it'll start doing that again when I create the next PR.

**Pull request merged**
