### PR TITLE
Get the docs working on RtD

### PR DESCRIPTION
**Pull request by Changaco**
WIP. @whit537 can you point RtD to this branch and paste me the build logs?

### CODE REVIEW

**Comment by whit537** [comment]
```
python -mvirtualenv --no-site-packages --no-download /home/docs/checkouts/readthedocs.org/user_builds/pando/envs/latest
python /home/docs/checkouts/readthedocs.org/user_builds/pando/envs/latest/bin/pip install --use-wheel -U --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/pando/.cache/pip sphinx==1.3.5 Pygments==2.1.3 setuptools==20.1.1 docutils==0.12 mkdocs==0.15.0 mock==1.0.1 pillow==2.6.1 git+https://github.com/rtfd/readthedocs-sphinx-ext.git@0.6-alpha#egg=readthedocs-sphinx-ext sphinx-rtd-theme==0.1.9 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.5.4 recommonmark==0.1.1
cat conf.py
python /home/docs/checkouts/readthedocs.org/user_builds/pando/envs/latest/bin/sphinx-build -T -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
python /home/docs/checkouts/readthedocs.org/user_builds/pando/envs/latest/bin/sphinx-build -T -b json -d _build/doctrees-json -D language=en . _build/json
python /home/docs/checkouts/readthedocs.org/user_builds/pando/envs/latest/bin/sphinx-build -T -b readthedocssinglehtmllocalmedia -d _build/doctrees-readthedocssinglehtmllocalmedia -D language=en . _build/localmedia
python /home/docs/checkouts/readthedocs.org/user_builds/pando/envs/latest/bin/sphinx-build -b latex -D language=en -d _build/doctrees . _build/latex
pdflatex -interaction=nonstopmode /home/docs/checkouts/readthedocs.org/user_builds/pando/checkouts/latest/docs/_build/latex/Pando.tex
makeindex -s python.ist Pando.idx
pdflatex -interaction=nonstopmode /home/docs/checkouts/readthedocs.org/user_builds/pando/checkouts/latest/docs/_build/latex/Pando.tex
mv -f /home/docs/checkouts/readthedocs.org/user_builds/pando/checkouts/latest/docs/_build/latex/Pando.pdf /home/docs/checkouts/readthedocs.org/user_builds/pando/artifacts/latest/sphinx_pdf/pando.pdf
python /home/docs/checkouts/readthedocs.org/user_builds/pando/envs/latest/bin/sphinx-build -T -b epub -d _build/doctrees-epub -D language=en . _build/epub
mv -f /home/docs/checkouts/readthedocs.org/user_builds/pando/checkouts/latest/docs/_build/epub/Pando.epub /home/docs/checkouts/readthedocs.org/user_builds/pando/artifacts/latest/sphinx_epub/pando.epub
```

**Comment by Changaco** [comment]
Ready for review.

Also, I now have a [RtD account](https://readthedocs.org/profiles/Changaco/), so you can add me as a maintainer on Aspen projects if you want.

**Comment by Changaco** [comment]
And here's my current plan for the next PRs:

- `pando.algorithms.website` → `pando.algorithm`
- complete/improve API reference
- import content from the old website

**Comment by whit537** [comment]
> Also, I now have a RtD account, so you can add me as a maintainer on Aspen projects if you want.

Done!

screen shot 2016-09-14 at 8 12 41 am

**Comment by whit537** [comment]
> `pando.algorithms.website` → `pando.algorithm` (or `website_algo[rithm]`)

I may start using the term "state chain" in the Aspen docs, whether or not we [rename](https://github.com/AspenWeb/algorithm.py/issues/3) the underlying library.

**Comment by whit537** [comment]
> complete/improve API reference
> import content from the old website

As I may have telegraphed at one point on https://github.com/AspenWeb/aspen.py/pull/32, I expect over there to have a "Tutorial" section preceding the "Reference."

**Comment by Changaco** [comment]
> I may start using the term "state chain" in the Aspen code and docs

Okay, let's go with `state_chain` then.

> I expect over there to have a "Tutorial" section preceding the "Reference."

Agreed. They should probably be separate pages, not sections of a giant page.

**Comment by whit537** [comment]
> They should probably be separate pages, not sections of a giant page.

Yeah, the reference can come from the docstrings of the individual modules, with the tutorial as the docstring of the main __init__.py.

**Comment by whit537** [comment]
... or did you mean in the HTML output? I'm +1 on separate HTML pages.

**Comment by Changaco** [comment]
Yes, I meant separate HTML pages, and thus probably separate `.rst` files.

**Comment by whit537** [comment]
@Changaco I believe Sphinx may let us control page splitting based on the depth of the doc structure, which was the option I was expecting to explore.

**Pull request merged**
